# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ToDo List' do
pod 'JTCalendar', '~> 1.0.0'
end

target 'ToDo ListTests' do
pod 'JTCalendar', '~> 1.0.0' 
end

pod 'MMWormhole', '~> 1.1.1'
